server:
    port: 9000
management:
    address: 127.0.0.1
    port: 9100
logging:
    level:
        attendance.application: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/kenshu
        username: postgres
        password: admin
        driverClassName: org.postgresql.Driver
    messages:
        encoding: UTF-8
    thymeleaf:
        cache: false
linecorp:
    platform:
        channel:
            channelId: 1
            channelSecret: 1
            callbackUrl: 1